### ISSUE TITLE
Emit failed transfer event in `transferQuiet`

### ISSUE THREAD

**Issue by mrdavey** [hCaptcha/hmt-token#12]
For the `transferQuiet` function, why not also emit a failed transfer event? I assume bulk transfers would also want to verify that all addresses received the relevant amounts correctly.

E.g. if msg.sender runs out of tokens mid way through the bulk transfer, you’d want an easy way to alert and resume the bulk transfer from the front end.

**Comment by rbval** [comment]
We want to keep `transfer` clean in a way that we want to just know if "Transfer didn't succeed" so we instead just return `true` / `false` in `transferQuiet`. Thank you for making the issue though. Closing now. Will reopen if we decide to change this.
