### ISSUE TITLE
Make sure to test in metamask

### ISSUE THREAD

**Issue by posix4e** [hCaptcha/hmt-token#34]
Post a screenshot here

**Comment by rbval** [comment]
<img width="354" alt="screen shot 2018-10-10 at 19 04 40" src="https://user-images.githubusercontent.com/6399810/46750298-5106fe00-ccc0-11e8-9fad-0e76e2716cdb.png">
<img width="357" alt="screen shot 2018-10-10 at 19 10 54" src="https://user-images.githubusercontent.com/6399810/46750309-56644880-ccc0-11e8-8c6f-b8681937cc95.png">

Deployed the token at https://rinkeby.etherscan.io/address/0x3c60289b690496df65bb6d1d56587bf12727552f . Did the transfer with the standard `transfer` method on remix.ethereum.org @posix4e
