### ISSUE TITLE
Add SafeMath revert check

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-token#40]
We  assume  the  intention  for  this  function  is  not  to  revert  thefunction invocation, and that the outer logic would handle the failures by checkingthe  return  value.   Consider  adding  anifcondition  such  asif (balances[_to] +_value < balances[_to])(...),  otherwisebalances[_to] = balances[_to].add(_value)will still have a chance to revert when therequirefailed inside theSafeMath.

**Comment by posix4e** [comment]
oh hah!
