### ISSUE TITLE
Push hmt-token to dockerhub

### ISSUE THREAD

**Issue by gaieges** [hCaptcha/hmt-token#6]
Either push at the end of the ci run, or via dockers infrastructure (former preferred)

**Comment by gaieges** [comment]
This actually is mostly done already (via dockerhub configuration, they build the images for us under Evin's account) .. however the delta from current is that we probably want to have travis push to the repo vs having dockerhub build for us, so that we have a bit more control over the tags, workflow, and ensure that the image gets built and deployed.  (plus can use the github ACL's)

Tbh I'd prob leave it the way it is for now until we have issues and need that control.

**Comment by rbval** [comment]
Is this task already done? We could separate the travis thing to a separate issue to not leave this hanging @gaieges

**Comment by gaieges** [comment]
the latter portion of the ticket is done, not the former. this issue would be for the former at this point.  would be fine the travis part was in a different ticket

**Comment by gaieges** [comment]
Moved to https://github.com/hCaptcha/hmt-token/issues/23
